<!-- Section A Propos -->
<div class="container p-5">
    <div class="rowPropos">
        <div class="col-lg-3 col-md-3">
            <h4 class="text-warning">
                <!-- <img src="assets/images/about/logo.png" alt="logo" /> --> <strong>Tricot by Nath</strong>
            </h4>

        </div>
        <div class="col-lg-9 col-md-9">
            <div class="about-us-content">
                <h3 class="text-warning">À propos</h3>
                <p class="text-justify">
                    Depuis la naissance de mon premier petit enfant, j'ai redécouvert le plaisir du crochet,
                    un art ancestral qui me permet de créer des pièces uniques et raffinées.
                    Chaque point, chaque maille est réalisé avec amour et minutie, pour vous offrir des créations de qualité irréprochable.<br /><br>

                    Mon inspiration ? La nature, les couleurs, les tendances et surtout l'envie de vous apporter une touche de douceur
                    et de chaleur dans votre quotidien. Que vous cherchiez un doudou pour votre enfant, un accessoire tendance
                    ou une pièce décorative originale, vous trouverez ici le cadeau parfait ou l'objet unique qui saura embellir votre intérieur.<br /><br>

                    Toutes mes créations sont réalisées avec des fils de qualité supérieure, soigneusement sélectionnés pour leur douceur,
                    leur résistance et leurs couleurs vibrantes. Je travaille avec passion et attention aux détails,
                    pour vous offrir des pièces durables et précieuses qui vous accompagneront longtemps.<br /><br>

                    En plus de mes créations originales, je vous propose également des modèles personnalisés.
                    Vous avez une idée précise en tête ? N'hésitez pas à me contacter, je serai ravie de la réaliser pour vous !<br /><br />

                    Visitez ma boutique en ligne et découvrez mon univers
                </p>
                <div class="signature">
                    <h2>Nathalie Hachelef</h2>
                </div>
            </div>
        </div>
    </div>
</div>