<div class="album py-5 bg-primary">
    <div class="container">
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><strong>Tricot By Nath : </strong> <span class="blink">Se connecter</span></div>
            <div class="divider-custom-line"></div>
        </div>


        <div class="row justify-content-center p-5">
            <div class="col-md-6 text-center text-warning">
                <form class="needs-validation" action="" method="post">
                    <h1 class="text-warning p-5">Veuillez vous connecter !</h1>

                    <div class="mb-3">
                        <label for="login" class="form-label">Login :</label>
                        <input type="text" class="form-control" id="login" name="login" placeholder="Jean Neymar" value="" required>
                        <div class="invalid-feedback">
                            Un login valide est requis.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="mdp" class="form-label">Mot de passe :</label>
                        <input type="password" class="form-control" id="mdp" name="mdp" placeholder="MotDePasse " value="" required>
                        <div class="invalid-feedback">
                            Un mot de passe valide est requis.
                        </div>
                    </div>

                    <div class="form-check mb-3">
                        <label class="form-check-label" for="flexCheckDefault">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault"> Se souvenir
                        </label>
                    </div>
                    <button class="w-100 btn btn-lg btn-warning mb-3" type="submit">Se connecter</button>
                </form>
            </div>
        </div>


    </div>