<div class="album py-5 bg-primary">
    <div class="container">
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><strong>Tricot By Nath : </strong> <span class="blink">Mon compte</span></div>
            <div class="divider-custom-line"></div>
        </div>

        <div class="row produit flex-nowrap">
            <div class="col-md-7 order-md-2 py-5">
                <h2 class="produit-heading text-white">Nom : <span class="text-warning"> TEST </span></h2>
                <h2 class="produit-heading text-white">Prénom : <span class="text-warning"> EnDur</span></h2>
                <h2 class="produit-heading text-white">Adresse : <span class="text-warning"> 404 rue Not Found, 59000 Ville</span></h2>
                <h2 class="produit-heading text-white">Email : <span class="text-warning"> testEnDur@notfound.com</span></h2>
                <h2 class="produit-heading text-white">Mot de passe : <span class="text-warning"> *****</span></h2>
                <h2 class="produit-heading"><a href="" class="text-white">Modifier le mot de passe ?</a></h2>
            </div>

            <div class="col-md-5 order-md-1 text-center">

                <img src="assets/images/avatar/harley.png" class="img-thumbnail-avatar rounded" alt="...">

            </div>

        </div>
    </div>