<div class="content">
    <h4 class="text-warning text-center"> Ajout d'une image </h4>
    <?php if ($ajoutImageOk) { ?>
        <div class="alert alert-dismissible alert-success text-center show" role="alert">
            Image ajouté avec succès !
        </div>
    <?php } ?>
    <form action="index.php?action=addImage" method="post">
        <div class="mb-3">
            <label for="inputTitre" class="form-label">Url :</label>
            <input type="text" class="form-control" id="url" name="url">
        </div>
        <div class="mb-3">
            <select class="form-select" name="idProduit" id="idProduit">
                <option value="">Selectionner le produit a qui ajouter une image additionnelle :</option>
                <?php foreach ($produits as $produit) { ?>
                    <option value="<?= $produit['id'] ?>"><?= $produit['nom'] ?></option>
                <?php } ?>

            </select>
        </div>
        <button type="submit" class="btn btn-primary" name="btAjout">Ajouter</button>
    </form>
</div>