<div class="content">
    <h4 class="text-warning text-center"> Ajout d'une sous-catégorie </h4>
    <?php if ($ajoutSousCatOk) { ?>
        <div class="alert alert-dismissible alert-success text-center show" role="alert">
            Sous-Catégorie ajouté avec succès !
        </div>
    <?php } ?>
    <form action="index.php?action=addSousCategorie" method="post">
        <div class="mb-3">
            <label for="inputTitre" class="form-label">Titre :</label>
            <input type="text" class="form-control" id="titreSousCat" name="titreSousCat">
        </div>
        <button type="submit" class="btn btn-primary" name="btAjout">Ajouter</button>
    </form>
</div>