</div>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center p-5">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-decoration-none">
                <h4 class="text-warning"><strong>Tricot By Nath</strong></h4>
            </a>
            <span class="mb-3 mb-md-0 text-primary">&copy; 2024 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex fs-2">
            <li class="ms-3"><a class="text-primary" href="#"><i class="fa-brands fa-instagram"></i></a></li>
            <li class="ms-3"><a class="text-primary" href="#"><i class="fa-brands fa-facebook"></i></a></li>
            <li class="ms-3"><a class="text-primary" href="#"><i class="fa-brands fa-snapchat"></i></a></li>
        </ul>
    </footer>
</div>