<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom p-5">
        <div class="col-md-4 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">

                <h4 class="text-warning"><strong>Tricot By Nath - Admin</strong></h4>
            </a>
        </div>

        <div class="col-md-3 text-end">
            <button type="button" class="btn btn-primary me-2">Login</button>
            <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
    </header>
</div>