<div class="container-flex">
    <div class="sidebar flex-shrink-0 p-3 bg-white">
        <ul class="list-unstyled ps-0">
            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
                    Accueil
                </button>
                <div class="collapse show" id="home-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="index.php" class="link-dark rounded">Dashboard</a></li>
                    </ul>
                </div>
            </li>

            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                    Produits
                </button>
                <div class="collapse" id="dashboard-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="index.php?action=produits" class="link-dark rounded">Liste des produits</a></li>
                        <li><a href="index.php?action=addProduit" class="link-dark rounded">Ajouter un produit</a></li>
                    </ul>
                </div>
            </li>
            <li class="mb-1">
                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                    Catégories
                </button>
                <div class="collapse" id="orders-collapse">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><a href="index.php?action=categories" class="link-dark rounded">Liste des catégories</a></li>
                        <li><a href="index.php?action=addCat" class="link-dark rounded">Ajouter une catégorie</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>