<div class="content">
    <h4 class="text-warning text-center"> Liste des produits </h4>
    <?php if ($delOK) { ?>
        <div class="alert alert-dismissible alert-success text-center show" role="alert">
            Produit supprimé avec succès !
        </div>
    <?php } ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Ref</th>
                <th scope="col">Nom</th>
                <th scope="col">Couleur</th>
                <th scope="col">Nombre de pelote</th>
                <th scope="col">Prix</th>
                <th scope="col">Description</th>
                <th scope="col">Image principale</th>
                <th scope="col">Favoris</th>
                <th scope="col">Categorie</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($produitsPourPageCourante as $produit) { ?>
                <tr>
                    <th scope="row"><?= $produit['id'] ?></th>
                    <th scope="row"><?= $produit['nom'] ?></th>
                    <th scope="row"><?= $produit['couleur'] ?></th>
                    <th scope="row"><?= $produit['nbPelote'] ?></th>
                    <th scope="row"><?= $produit['prix'] ?>€</th>
                    <th scope="row" class="text-truncate-custom"><?= $produit['description'] ?></th>
                    <th scope="row"><?= $produit['imagePrinc'] ?></th>
                    <th scope="row"><?php if ($produit['favoris']) { ?>
                            Oui
                        <?php } else { ?>
                            Non
                        <?php } ?></th>
                    <th scope="row"><?= $produit['id_categorie'] ?></th>
                    <th scope="row">
                        <a href="index.php?action=upProduit&idProd=<?= $produit['id'] ?>" class="btn btn-success"><i class="fa-solid fa-pen"></i></a>
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<?= $produit['id']; ?>">
                            <i class="fa-solid fa-trash-can"></i>
                        </button>
                    </th>

                    <!-- Modal Delete Button -->
                    <div class="modal fade" id="deleteModal<?= $produit['id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-xl" role="document">
                            <div class="modal-content">
                                <div class="modal-header text-center">
                                    <h1 class="modal-title text-warning" id="deleteModalLabel">Suppression d'un produit</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-center">
                                    <p class="fs-3">Voulez-vous vraiment supprimer le produit : <span class="text-warning"><?= $produit['nom'] ?></span></p>
                                </div>
                                <div class="modal-footer">
                                    <!-- Formulaire pour soumettre la suppression -->
                                    <form action="index.php?action=delProduit&idProd=<?= $produit['id']; ?>" method="POST">
                                        <button type="submit" class="btn btn-danger" name="btDelete">Supprimer</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-end pt-5">
            <li class="page-item <?= ($pageCourante == 1) ? 'disabled' : '' ?>">
                <a class="page-link" href="index.php?action=produits&page=<?= $pageCourante - 1 ?>">Précédent</a>
            </li>
            <?php for ($page = 1; $page <= $totalPages; $page++) { ?>
                <li class="page-item <?= ($page == $pageCourante) ? 'active' : '' ?>">
                    <a class="page-link" href="index.php?action=produits&page=<?= $page ?>"><?= $page ?></a>
                </li>
            <?php } ?>
            <li class="page-item <?= ($pageCourante == $totalPages) ? 'disabled' : '' ?>">
                <a class="page-link" href="index.php?action=produits&page=<?= $pageCourante + 1 ?>">Suivant</a>
            </li>
        </ul>
    </nav>
</div>