<div class="content">
    <h4 class="text-warning text-center"> Modification d'une image </h4>
    <?php if ($modifImageOk) { ?>
        <div class="alert alert-dismissible alert-success text-center show" role="alert">
            Image modifiée avec succès !
        </div>
    <?php } ?>
    <form action="index.php?action=upCategorie&idCat=<?= $imageUp['id'] ?>" method="post">
        <div class="mb-3">
            <label for="inputUrl" class="form-label">Url :</label>
            <input type="text" class="form-control" id="url" name="url" value="<?= $imageUp['url'] ?>">
        </div>

        <div class="mb-3">
            <select class="form-select" name="idProduit" id="idProduit">
                <option value="">Selectionner le produit a qui ajouter une image additionnelle :</option>
                <?php foreach ($produits as $produit) { ?>
                    <?php if ($produit['id'] == $imageUp['id_produit']) { ?>
                        <option value="<?= $produit['id'] ?>" selected><?= $produit['nom'] ?></option>
                    <?php } else { ?>
                        <option value="<?= $produit['id'] ?>"><?= $produit['nom'] ?></option>
                    <?php } ?>
                <?php } ?>

            </select>
        </div>
        <button type="submit" class="btn btn-primary" name="btModif">Modifier</button>
    </form>
</div>