<div class="content">
    <h4 class="text-warning text-center"> Modification d'une sous-catégorie </h4>
    <?php if ($modifSousCatOk) { ?>
        <div class="alert alert-dismissible alert-success text-center show" role="alert">
            Sous-catégorie modifié avec succès !
        </div>
    <?php } ?>
    <form action="index.php?action=upSousCategorie&idSousCat=<?= $sousCatUp['id'] ?>" method="post">
        <div class="mb-3">
            <label for="inputTitre" class="form-label">Titre :</label>
            <input type="text" class="form-control" id="titreSousCat" name="titreSousCat" value="<?= $sousCatUp['titre'] ?>">
        </div>
        <button type="submit" class="btn btn-primary" name="btModif">Modifier</button>
    </form>
</div>